### ISSUE TITLE
Example build error

### ISSUE THREAD

**Issue by a212** [fubark/cosmic#24]
Tried to build with: zig build run -Dpath="ui/examples/counter.zig" -Dgraphics -Drelease-safe
And got:
./GitRepoStep.zig:183:10: error: type '@typeInfo(@typeInfo(@TypeOf(std.child_process.ChildProcess.init)).Fn.return_type.?).ErrorUnion.error_set!*std.child_process.ChildProcess' does not support field access
    child.stdin_behavior = .Ignore;
         ^

**Comment by fubark** [comment]
Make sure you have a recent version (dev/master) of the zig compiler. https://ziglang.org/documentation/master/std/#std;ChildProcess.init shows that it doesn't return an error union.

**Comment by fubark** [comment]
You can get the latest here: https://ziglang.org/download/

**Comment by a212** [comment]
Yeah, sorry, used the old version of 0.10.0-dev (.804)
